# Generated by Django 2.0.1 on 2018-01-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a file name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FileHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_modified', models.DateField(blank=True, null=True)),
                ('server_modified', models.DateField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('n', 'Non-existent'), ('t', 'Tracked'), ('m', 'Modified')], default='m', help_text='Status of the file', max_length=1)),
                ('file_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.FileEntity')),
            ],
        ),
    ]
