# Generated by Django 2.0.1 on 2018-01-13 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filehistory',
            name='status',
        ),
        migrations.AddField(
            model_name='fileentity',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Non-existent'), ('t', 'Tracked'), ('m', 'Modified')], default='m', help_text='Status of the file', max_length=1),
        ),
        migrations.AlterField(
            model_name='filehistory',
            name='client_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filehistory',
            name='file_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tracker.FileEntity'),
        ),
        migrations.AlterField(
            model_name='filehistory',
            name='server_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
