# Generated by Django 2.0.1 on 2018-01-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180113_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehistory',
            name='inserted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
