# Generated by Django 2.0.1 on 2018-01-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20180115_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentity',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('n', 'Non-existent'), ('t', 'Tracked'), ('m', 'Modified')], default='p', help_text='Status of the file', max_length=1),
        ),
    ]
